apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
  labels:
    type: wp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    type: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-1